name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs whenever you push to main

permissions:
  contents: write  # Needed for pushing to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # Install dependencies
      - run: npm ci

      # Build the project (base path handled by vite.config.ts)
      - run: npm run build

      # Deploy the "dist" folder to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
